
import { Button } from '@/components/ui/button';
import { Sparkles, Brain } from 'lucide-react';

interface SummaryDisplayProps {
  summary?: string;
  isGenerating: boolean;
  onGenerate: () => void;
}

export const SummaryDisplay = ({ summary, isGenerating, onGenerate }: SummaryDisplayProps) => {
  if (summary && !isGenerating) {
    return (
      <div className="bg-gradient-to-r from-indigo-50 to-purple-50 p-6 rounded-lg border border-indigo-200">
        <p className="text-gray-700 leading-relaxed mb-4">{summary}</p>
        
        <div className="flex items-center justify-between">
          <span className="text-sm text-indigo-600 flex items-center gap-1">
            <Sparkles className="w-3 h-3" />
            Generated by Advanced AI Analysis
          </span>
          
          <Button
            onClick={onGenerate}
            variant="outline"
            size="sm"
            disabled={isGenerating}
            className="border-indigo-200 text-indigo-600 hover:bg-indigo-50"
          >
            <Sparkles className="w-3 h-3 mr-1" />
            Regenerate
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-gray-50 p-6 rounded-lg text-center">
      <Brain className="w-12 h-12 mx-auto text-gray-400 mb-3" />
      <p className="text-gray-600 mb-4">
        Get an AI-powered summary that highlights main themes, key arguments, and important conclusions from your note.
      </p>
      <Button
        onClick={onGenerate}
        className="bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white"
      >
        <Sparkles className="w-4 h-4 mr-2" />
        Analyze & Summarize
      </Button>
    </div>
  );
};
